services:
  web:
    build: . # Baut das Image basierend auf dem Dockerfile im aktuellen Verzeichnis
    network_mode: "host" # Host-Netzwerk nutzen, da veth-Paare im aktuellen Setup nicht unterstützt sind
    command: flask run --host=0.0.0.0 --port=5001
    volumes:
      # Mountet das gesamte lokale Projektverzeichnis in das /app Verzeichnis im Container.
      # Dadurch werden Code-Änderungen live übernommen und im Container erstellte Dateien
      # (wie app.db und der migrations-Ordner, wenn sie in /app erstellt werden)
      # bleiben auf dem Host-System erhalten.
      - .:/app
    environment:
      # Überschreibt ggf. ENV-Variablen aus dem Dockerfile oder setzt sie, falls nicht im Dockerfile
      - FLASK_APP=app:create_app # Wichtig für die Flask-Anwendungsfabrik
      - FLASK_DEBUG=1
      - PYTHONPATH=/app # Stellt sicher, dass Python Module im /app Verzeichnis findet
      # - DATABASE_URL=sqlite:////app/app.db # Könnte explizit gesetzt werden, aber deine config.py sollte das handhaben
